#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 14
#SBATCH --time 00:10:00
#SBATCH --partition=teach_cpu
#SBATCH --account=COSC028844
#SBATCH --output d2q9-bgk-%j.out
#SBATCH --exclusive 

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
source env.sh
advixe-cl --project-dir=./advixe-res --collect=survey -- ./d2q9-bgk input_128x128.params obstacles_128x128.dat
advixe-cl --project-dir=./advixe-res --collect=tripcounts -flop -- ./d2q9-bgk input_128x128.params obstacles_128x128.dat
advixe-cl --project-dir=./advixe-res --report=survey --format=text --report-outputs=./advixe-res/output-survey.txt
gprof -l d2q9-bgk gmon.out
#make check
#./d2q9-bgk input_128x256.params obstacles_128x256.dat
#./d2q9-bgk input_256x256.params obstacles_256x256.dat
#./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
