#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 14
#SBATCH --time 00:15:00
#SBATCH --partition=teach_cpu
#SBATCH --account=COSC028844
#SBATCH --output d2q9-bgk-parallel-%j.out
#SBATCH --exclusive 

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
echo "----------------------------------------"
OMP_NUM_THREADS=1
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=2
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=26
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=25
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=24
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=23
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=22
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=21
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=20
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=19
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=18
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=17
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=16
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=15
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=14
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=13
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=12
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=11
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=10
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=9
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=8
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=7
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=6
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=5
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=4
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=3
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=2
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

echo "----------------------------------------"
OMP_NUM_THREADS=1
echo num threads is $OMP_NUM_THREADS 
./d2q9-bgk input_128x128.params obstacles_128x128.dat
./d2q9-bgk input_128x256.params obstacles_128x256.dat
./d2q9-bgk input_256x256.params obstacles_256x256.dat
./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
